# Generated by Django 5.2.14 on 2026-06-15 11:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ballot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('opens_at', models.DateTimeField()),
                ('closes_at', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ballots_created', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BallotOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200)),
                ('display_order', models.PositiveSmallIntegerField(default=0)),
                ('ballot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='voting.ballot')),
            ],
            options={
                'ordering': ['display_order'],
            },
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cast_at', models.DateTimeField(auto_now_add=True)),
                ('ballot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='votes', to='voting.ballot')),
                ('option', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='votes', to='voting.ballotoption')),
                ('voter', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='votes_cast', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('ballot', 'voter')},
            },
        ),
    ]
