# Generated by Django 5.2.14 on 2026-06-26 11:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Broadcast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=200)),
                ('body', models.TextField()),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('recipient_filter', models.CharField(choices=[('ALL', 'All'), ('ACTIVE', 'Active'), ('ADMINS', 'Admins')], max_length=20)),
                ('recipient_count', models.PositiveIntegerField()),
                ('sent_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-sent_at'],
            },
        ),
        migrations.CreateModel(
            name='ChatExport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='whatsapp/%Y/%m/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('source_group_name', models.CharField(blank=True, max_length=200)),
                ('message_count', models.PositiveIntegerField(default=0)),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='ChatAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('results', models.JSONField(default=dict)),
                ('chat_export', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analyses', to='whatsapp.chatexport')),
            ],
            options={
                'ordering': ['-generated_at'],
            },
        ),
    ]
